# Generated by Django 3.2.5 on 2021-09-27 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lecture',
            new_name='Lectures',
        ),
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Teachers',
        ),
    ]
